package problems_1_100.problems_1_10

object Problem2 extends App {
  println("Each new term in the Fibonacci sequence is generated by adding the previous two terms. ")
  println("By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
  println("By considering the terms in the Fibonacci sequence whose values do not exceed four million, " +
    "find the sum of the even-valued terms.")

  lazy val fibonacci: Stream[Int] = 0 #:: fibonacci.scanLeft(1)(_ + _)
  val value = fibonacci.takeWhile(_ <= 4000000).filter(_ % 2 == 0).sum

  println(s"The sum of the even-valued terms whose values do not exceed four million is $value")

}
